"""make store_name and store_email nullable in shop_settings

Revision ID: 1952ead37c3b
Revises: 5b2e35a36335
Create Date: 2026-01-07 18:14:55.297962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1952ead37c3b'
down_revision: Union[str, None] = '5b2e35a36335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
