"""add original_price to products

Revision ID: 54f379108ff0
Revises: f72bf97812c8
Create Date: 2026-01-07 18:37:46.675619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f379108ff0'
down_revision: Union[str, None] = 'f72bf97812c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_index('ix_shop_settings_shop_id', table_name='shop_settings')
    op.create_index(op.f('ix_shop_settings_shop_id'), 'shop_settings', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_settings_shop_id'), table_name='shop_settings')
    op.create_index('ix_shop_settings_shop_id', 'shop_settings', ['shop_id'], unique=False)
    op.drop_column('products', 'original_price')
    # ### end Alembic commands ###
