"""Add missing fields to user model

Revision ID: 5b2e35a36335
Revises: 27c177863249
Create Date: 2026-01-07 16:56:56.953283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2e35a36335'
down_revision: Union[str, None] = '27c177863249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('registration_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('profile_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_completed_at')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'registration_ip')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'login_count')
    # ### end Alembic commands ###
