"""initial

Revision ID: 7031e5e98cb4
Revises: 
Create Date: 2025-12-17 14:33:48.558126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7031e5e98cb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_profile_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_email'), 'otps', ['email'], unique=False)
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('join_password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_table('analytics_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('report_name', sa.String(length=200), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generation_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_reports_id'), 'analytics_reports', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_reports_period_end'), 'analytics_reports', ['period_end'], unique=False)
    op.create_index(op.f('ix_analytics_reports_period_start'), 'analytics_reports', ['period_start'], unique=False)
    op.create_index(op.f('ix_analytics_reports_report_type'), 'analytics_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_analytics_reports_shop_id'), 'analytics_reports', ['shop_id'], unique=False)
    op.create_index('ix_analytics_shop_type_period', 'analytics_reports', ['shop_id', 'report_type', 'period_start'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('product_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_shop_id'), 'categories', ['shop_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('addresses', sa.JSON(), nullable=True),
    sa.Column('customer_type', sa.String(length=50), nullable=True),
    sa.Column('customer_group', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_newsletter_subscribed', sa.Boolean(), nullable=True),
    sa.Column('account_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('first_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clv', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('referral_code', sa.String(length=100), nullable=True),
    sa.Column('referred_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['referred_by'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_referral_code'), 'customers', ['referral_code'], unique=False)
    op.create_index('ix_customers_shop_email', 'customers', ['shop_id', 'email'], unique=False)
    op.create_index(op.f('ix_customers_shop_id'), 'customers', ['shop_id'], unique=False)
    op.create_index('ix_customers_shop_phone', 'customers', ['shop_id', 'phone'], unique=False)
    op.create_index('ix_customers_shop_type', 'customers', ['shop_id', 'customer_type'], unique=False)
    op.create_table('daily_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_items_sold', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_order_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_customers', sa.Integer(), nullable=True),
    sa.Column('returning_customers', sa.Integer(), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=True),
    sa.Column('unique_visitors', sa.Integer(), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=True),
    sa.Column('bounce_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('top_products', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_analytics_date'), 'daily_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_daily_analytics_id'), 'daily_analytics', ['id'], unique=False)
    op.create_index('ix_daily_analytics_shop_date', 'daily_analytics', ['shop_id', 'date'], unique=True)
    op.create_index(op.f('ix_daily_analytics_shop_id'), 'daily_analytics', ['shop_id'], unique=False)
    op.create_table('shop_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('theme_name', sa.String(length=100), nullable=True),
    sa.Column('color_scheme', sa.JSON(), nullable=True),
    sa.Column('font_settings', sa.JSON(), nullable=True),
    sa.Column('layout_settings', sa.JSON(), nullable=True),
    sa.Column('header_settings', sa.JSON(), nullable=True),
    sa.Column('footer_settings', sa.JSON(), nullable=True),
    sa.Column('homepage_settings', sa.JSON(), nullable=True),
    sa.Column('product_page_settings', sa.JSON(), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('custom_js', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('banner_images', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_designs_id'), 'shop_designs', ['id'], unique=False)
    op.create_index(op.f('ix_shop_designs_shop_id'), 'shop_designs', ['shop_id'], unique=True)
    op.create_table('shop_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_members_id'), 'shop_members', ['id'], unique=False)
    op.create_table('shop_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=False),
    sa.Column('store_email', sa.String(length=255), nullable=False),
    sa.Column('store_phone', sa.String(length=50), nullable=True),
    sa.Column('store_currency', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('business_hours', sa.JSON(), nullable=True),
    sa.Column('order_settings', sa.JSON(), nullable=True),
    sa.Column('shipping_settings', sa.JSON(), nullable=True),
    sa.Column('payment_settings', sa.JSON(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('seo_settings', sa.JSON(), nullable=True),
    sa.Column('social_media', sa.JSON(), nullable=True),
    sa.Column('features_enabled', sa.JSON(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_settings_id'), 'shop_settings', ['id'], unique=False)
    op.create_index(op.f('ix_shop_settings_shop_id'), 'shop_settings', ['shop_id'], unique=True)
    op.create_table('traffic_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('campaign', sa.String(length=200), nullable=True),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('unique_visitors', sa.Integer(), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=True),
    sa.Column('avg_session_duration', sa.Integer(), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_sources_campaign'), 'traffic_sources', ['campaign'], unique=False)
    op.create_index(op.f('ix_traffic_sources_date'), 'traffic_sources', ['date'], unique=False)
    op.create_index(op.f('ix_traffic_sources_id'), 'traffic_sources', ['id'], unique=False)
    op.create_index('ix_traffic_sources_shop_date_source', 'traffic_sources', ['shop_id', 'date', 'source_type', 'source_name'], unique=True)
    op.create_index(op.f('ix_traffic_sources_shop_id'), 'traffic_sources', ['shop_id'], unique=False)
    op.create_index(op.f('ix_traffic_sources_source_name'), 'traffic_sources', ['source_name'], unique=False)
    op.create_index(op.f('ix_traffic_sources_source_type'), 'traffic_sources', ['source_type'], unique=False)
    op.create_table('category_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('total_products', sa.Integer(), nullable=True),
    sa.Column('active_products', sa.Integer(), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Integer(), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_stats_category_id'), 'category_stats', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_stats_id'), 'category_stats', ['id'], unique=False)
    op.create_table('customer_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_notes_customer_id'), 'customer_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_notes_id'), 'customer_notes', ['id'], unique=False)
    op.create_index(op.f('ix_customer_notes_shop_id'), 'customer_notes', ['shop_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('customer_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', 'FAILED', name='orderstatus'), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'AUTHORIZED', 'PAID', 'PARTIALLY_PAID', 'REFUNDED', 'VOIDED', 'FAILED', name='paymentstatus'), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'WECHAT_PAY', 'ALIPAY', 'BANK_TRANSFER', 'PAYPAL', 'OTHER', name='paymentmethod'), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('shipping_method', sa.Enum('STANDARD', 'EXPRESS', 'PICKUP', 'DIGITAL', name='shippingmethod'), nullable=True),
    sa.Column('shipping_tracking_number', sa.String(length=100), nullable=True),
    sa.Column('shipping_carrier', sa.String(length=100), nullable=True),
    sa.Column('estimated_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipping_address', sa.JSON(), nullable=True),
    sa.Column('billing_address', sa.JSON(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('marketing_source', sa.String(length=100), nullable=True),
    sa.Column('referral_code', sa.String(length=100), nullable=True),
    sa.Column('coupon_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_coupon_code'), 'orders', ['coupon_code'], unique=False)
    op.create_index(op.f('ix_orders_customer_email'), 'orders', ['customer_email'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index('ix_orders_customer_shop', 'orders', ['customer_id', 'shop_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_payment_reference'), 'orders', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_shipping_tracking_number'), 'orders', ['shipping_tracking_number'], unique=False)
    op.create_index('ix_orders_shop_date', 'orders', ['shop_id', 'order_date'], unique=False)
    op.create_index(op.f('ix_orders_shop_id'), 'orders', ['shop_id'], unique=False)
    op.create_index('ix_orders_shop_status', 'orders', ['shop_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('compare_at_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('manage_stock', sa.Boolean(), nullable=True),
    sa.Column('allow_backorders', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', 'OUT_OF_STOCK', 'DISCONTINUED', name='productstatus'), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=True),
    sa.Column('requires_shipping', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight_unit', sa.String(length=10), nullable=True),
    sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dimensions_unit', sa.String(length=10), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=True),
    sa.Column('wishlist_count', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_is_featured'), 'products', ['is_featured'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index('ix_products_price_range', 'products', ['shop_id', 'price', 'sale_price'], unique=False)
    op.create_index(op.f('ix_products_shop_id'), 'products', ['shop_id'], unique=False)
    op.create_index('ix_products_shop_status', 'products', ['shop_id', 'status'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index('ix_products_stock_status', 'products', ['shop_id', 'stock_quantity', 'status'], unique=False)
    op.create_table('product_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('unique_views', sa.Integer(), nullable=True),
    sa.Column('add_to_cart', sa.Integer(), nullable=True),
    sa.Column('remove_from_cart', sa.Integer(), nullable=True),
    sa.Column('purchases', sa.Integer(), nullable=True),
    sa.Column('quantity_sold', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('wishlist_adds', sa.Integer(), nullable=True),
    sa.Column('wishlist_removes', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_analytics_date'), 'product_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_product_analytics_id'), 'product_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_product_analytics_product_id'), 'product_analytics', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_analytics_shop_id'), 'product_analytics', ['shop_id'], unique=False)
    op.create_index('ix_product_analytics_shop_product_date', 'product_analytics', ['shop_id', 'product_id', 'date'], unique=True)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('variant_name', sa.String(length=200), nullable=True),
    sa.Column('variant_attributes', sa.JSON(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('product_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('ix_product_analytics_shop_product_date', table_name='product_analytics')
    op.drop_index(op.f('ix_product_analytics_shop_id'), table_name='product_analytics')
    op.drop_index(op.f('ix_product_analytics_product_id'), table_name='product_analytics')
    op.drop_index(op.f('ix_product_analytics_id'), table_name='product_analytics')
    op.drop_index(op.f('ix_product_analytics_date'), table_name='product_analytics')
    op.drop_table('product_analytics')
    op.drop_index('ix_products_stock_status', table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index('ix_products_shop_status', table_name='products')
    op.drop_index(op.f('ix_products_shop_id'), table_name='products')
    op.drop_index('ix_products_price_range', table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_featured'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('ix_orders_shop_status', table_name='orders')
    op.drop_index(op.f('ix_orders_shop_id'), table_name='orders')
    op.drop_index('ix_orders_shop_date', table_name='orders')
    op.drop_index(op.f('ix_orders_shipping_tracking_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_reference'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index('ix_orders_customer_shop', table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_email'), table_name='orders')
    op.drop_index(op.f('ix_orders_coupon_code'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customer_notes_shop_id'), table_name='customer_notes')
    op.drop_index(op.f('ix_customer_notes_id'), table_name='customer_notes')
    op.drop_index(op.f('ix_customer_notes_customer_id'), table_name='customer_notes')
    op.drop_table('customer_notes')
    op.drop_index(op.f('ix_category_stats_id'), table_name='category_stats')
    op.drop_index(op.f('ix_category_stats_category_id'), table_name='category_stats')
    op.drop_table('category_stats')
    op.drop_index(op.f('ix_traffic_sources_source_type'), table_name='traffic_sources')
    op.drop_index(op.f('ix_traffic_sources_source_name'), table_name='traffic_sources')
    op.drop_index(op.f('ix_traffic_sources_shop_id'), table_name='traffic_sources')
    op.drop_index('ix_traffic_sources_shop_date_source', table_name='traffic_sources')
    op.drop_index(op.f('ix_traffic_sources_id'), table_name='traffic_sources')
    op.drop_index(op.f('ix_traffic_sources_date'), table_name='traffic_sources')
    op.drop_index(op.f('ix_traffic_sources_campaign'), table_name='traffic_sources')
    op.drop_table('traffic_sources')
    op.drop_index(op.f('ix_shop_settings_shop_id'), table_name='shop_settings')
    op.drop_index(op.f('ix_shop_settings_id'), table_name='shop_settings')
    op.drop_table('shop_settings')
    op.drop_index(op.f('ix_shop_members_id'), table_name='shop_members')
    op.drop_table('shop_members')
    op.drop_index(op.f('ix_shop_designs_shop_id'), table_name='shop_designs')
    op.drop_index(op.f('ix_shop_designs_id'), table_name='shop_designs')
    op.drop_table('shop_designs')
    op.drop_index(op.f('ix_daily_analytics_shop_id'), table_name='daily_analytics')
    op.drop_index('ix_daily_analytics_shop_date', table_name='daily_analytics')
    op.drop_index(op.f('ix_daily_analytics_id'), table_name='daily_analytics')
    op.drop_index(op.f('ix_daily_analytics_date'), table_name='daily_analytics')
    op.drop_table('daily_analytics')
    op.drop_index('ix_customers_shop_type', table_name='customers')
    op.drop_index('ix_customers_shop_phone', table_name='customers')
    op.drop_index(op.f('ix_customers_shop_id'), table_name='customers')
    op.drop_index('ix_customers_shop_email', table_name='customers')
    op.drop_index(op.f('ix_customers_referral_code'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_shop_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_analytics_shop_type_period', table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_shop_id'), table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_report_type'), table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_period_start'), table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_period_end'), table_name='analytics_reports')
    op.drop_index(op.f('ix_analytics_reports_id'), table_name='analytics_reports')
    op.drop_table('analytics_reports')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_email'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
