"""make store_name and store_email nullable in shop_settings

Revision ID: f72bf97812c8
Revises: 1952ead37c3b
Create Date: 2026-01-07 18:19:22.157983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72bf97812c8'
down_revision: Union[str, None] = '1952ead37c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_settings', 'store_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('shop_settings', 'store_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_shop_settings_shop_id', table_name='shop_settings')
    op.create_index('ix_shop_settings_shop_id', 'shop_settings', ['shop_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shop_settings_shop_id', table_name='shop_settings')
    op.create_index('ix_shop_settings_shop_id', 'shop_settings', ['shop_id'], unique=False)
    op.alter_column('shop_settings', 'store_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('shop_settings', 'store_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
