"""add ip_address and user_agent to otp table

Revision ID: 27c177863249
Revises: 14e39437fe64
Create Date: 2026-01-04 14:26:18.657240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c177863249'
down_revision: Union[str, None] = '14e39437fe64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('otps', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('otps', sa.Column('purpose', sa.String(length=50), nullable=True))
    op.create_index('idx_otp_email_created', 'otps', ['email', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_otp_email_created', table_name='otps')
    op.drop_column('otps', 'purpose')
    op.drop_column('otps', 'user_agent')
    op.drop_column('otps', 'ip_address')
    # ### end Alembic commands ###
