"""Fix model relationships and enums

Revision ID: f3001a77ffd5
Revises: 7031e5e98cb4
Create Date: 2025-12-31 16:06:07.483281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3001a77ffd5'
down_revision: Union[str, None] = '7031e5e98cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'notes')
    op.drop_index('ix_products_status', table_name='products')
    op.add_column('shop_designs', sa.Column('theme_version', sa.String(length=20), nullable=True))
    op.add_column('shop_designs', sa.Column('theme_author', sa.String(length=100), nullable=True))
    op.add_column('shop_designs', sa.Column('category_page_settings', sa.JSON(), nullable=True))
    op.add_column('shop_designs', sa.Column('cart_settings', sa.JSON(), nullable=True))
    op.add_column('shop_designs', sa.Column('logo_alt_text', sa.String(length=200), nullable=True))
    op.add_column('shop_designs', sa.Column('custom_head_html', sa.Text(), nullable=True))
    op.add_column('shop_designs', sa.Column('custom_footer_html', sa.Text(), nullable=True))
    op.add_column('shop_designs', sa.Column('seo_title_template', sa.String(length=200), nullable=True))
    op.add_column('shop_designs', sa.Column('seo_description_template', sa.String(length=500), nullable=True))
    op.add_column('shop_designs', sa.Column('seo_image_url', sa.String(length=500), nullable=True))
    op.add_column('shop_designs', sa.Column('mobile_settings', sa.JSON(), nullable=True))
    op.add_column('shop_designs', sa.Column('performance_settings', sa.JSON(), nullable=True))
    op.add_column('shop_designs', sa.Column('last_updated_by', sa.Integer(), nullable=True))
    op.drop_index('ix_shop_designs_shop_id', table_name='shop_designs')
    op.create_index(op.f('ix_shop_designs_shop_id'), 'shop_designs', ['shop_id'], unique=True)
    op.create_foreign_key(None, 'shop_designs', 'users', ['last_updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_designs', type_='foreignkey')
    op.drop_index(op.f('ix_shop_designs_shop_id'), table_name='shop_designs')
    op.create_index('ix_shop_designs_shop_id', 'shop_designs', ['shop_id'], unique=False)
    op.drop_column('shop_designs', 'last_updated_by')
    op.drop_column('shop_designs', 'performance_settings')
    op.drop_column('shop_designs', 'mobile_settings')
    op.drop_column('shop_designs', 'seo_image_url')
    op.drop_column('shop_designs', 'seo_description_template')
    op.drop_column('shop_designs', 'seo_title_template')
    op.drop_column('shop_designs', 'custom_footer_html')
    op.drop_column('shop_designs', 'custom_head_html')
    op.drop_column('shop_designs', 'logo_alt_text')
    op.drop_column('shop_designs', 'cart_settings')
    op.drop_column('shop_designs', 'category_page_settings')
    op.drop_column('shop_designs', 'theme_author')
    op.drop_column('shop_designs', 'theme_version')
    op.create_index('ix_products_status', 'products', ['status'], unique=False)
    op.add_column('customers', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
